-- F1.1: Float -> Decimal (NUMERIC) for money, NAV, units, FX, performance fields.
-- Generated via prisma migrate diff; reviewed: no DROP COLUMN.

-- AlterTable
ALTER TABLE "Account" ALTER COLUMN "balanceLocal" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "balanceCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "interestRatePct" SET DATA TYPE DECIMAL(7,4);

-- AlterTable
ALTER TABLE "AdvisorJournal" ALTER COLUMN "impactCzk" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "AllocationPlan" ALTER COLUMN "totalAvailableCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "fixedExpensesCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "reservedEventsCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "investableCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "emergencyTopupCzk" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "Cashflow" ALTER COLUMN "amountCzk" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "ExpenseCommitment" ALTER COLUMN "amountCzk" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "FXRate" ALTER COLUMN "rate" SET DATA TYPE DECIMAL(14,6);

-- AlterTable
ALTER TABLE "HistoricalReturn" ALTER COLUMN "return1m" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "return3m" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "return6m" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "return1y" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "return3y" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "return5y" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "return10y" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "volatility" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "sharpe" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "maxDrawdown" SET DATA TYPE DECIMAL(10,6);

-- AlterTable
ALTER TABLE "Holding" ALTER COLUMN "units" SET DATA TYPE DECIMAL(20,8),
ALTER COLUMN "nav" SET DATA TYPE DECIMAL(14,4),
ALTER COLUMN "currentValueCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "monthlySipCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "interestRatePct" SET DATA TYPE DECIMAL(7,4);

-- AlterTable
ALTER TABLE "IncomeEvent" ALTER COLUMN "amountLocal" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "amountCzk" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "IndiaFixedDeposit" ALTER COLUMN "principalInr" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "interestRatePct" SET DATA TYPE DECIMAL(7,4);

-- AlterTable
ALTER TABLE "IndiaIntelligence" ALTER COLUMN "value" SET DATA TYPE DECIMAL(14,4),
ALTER COLUMN "previousValue" SET DATA TYPE DECIMAL(14,4);

-- AlterTable
ALTER TABLE "IndiaMutualFund" ALTER COLUMN "units" SET DATA TYPE DECIMAL(20,8),
ALTER COLUMN "avgNavInr" SET DATA TYPE DECIMAL(14,4),
ALTER COLUMN "currentNavInr" SET DATA TYPE DECIMAL(14,4),
ALTER COLUMN "sipAmountInr" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "Instrument" ALTER COLUMN "terPct" SET DATA TYPE DECIMAL(7,4),
ALTER COLUMN "lastPrice" SET DATA TYPE DECIMAL(14,4),
ALTER COLUMN "return1yr" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "return3yr" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "return5yr" SET DATA TYPE DECIMAL(10,6);

-- AlterTable
ALTER TABLE "InstrumentLibrary" ALTER COLUMN "terPct" SET DATA TYPE DECIMAL(7,4),
ALTER COLUMN "fundSizeM" SET DATA TYPE DECIMAL(14,4),
ALTER COLUMN "trackingError" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "lastPrice" SET DATA TYPE DECIMAL(14,4),
ALTER COLUMN "return1yr" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "return3yr" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "return5yr" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "return10yr" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "score" SET DATA TYPE DECIMAL(10,6);

-- AlterTable
ALTER TABLE "NavHistory" ALTER COLUMN "nav" SET DATA TYPE DECIMAL(14,4);

-- AlterTable
ALTER TABLE "PriceHistory" ALTER COLUMN "price" SET DATA TYPE DECIMAL(14,4);

-- AlterTable
ALTER TABLE "RecommendationOutcome" ALTER COLUMN "estimatedImpactCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "actualImpactCzk" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "Settings" ALTER COLUMN "targetEquityPct" SET DATA TYPE DECIMAL(7,4),
ALTER COLUMN "targetBondsPct" SET DATA TYPE DECIMAL(7,4),
ALTER COLUMN "targetCashPct" SET DATA TYPE DECIMAL(7,4),
ALTER COLUMN "targetWealthCzk" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "SipExecution" ALTER COLUMN "amountCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "amountLocal" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "navAtExecution" SET DATA TYPE DECIMAL(14,4),
ALTER COLUMN "unitsAcquired" SET DATA TYPE DECIMAL(20,8);

-- AlterTable
ALTER TABLE "Snapshot" ALTER COLUMN "netWorthCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "netWorthEur" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "investedCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "gainCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "gainPct" SET DATA TYPE DECIMAL(7,4),
ALTER COLUMN "xirr" SET DATA TYPE DECIMAL(10,6),
ALTER COLUMN "equityPct" SET DATA TYPE DECIMAL(7,4),
ALTER COLUMN "bondsPct" SET DATA TYPE DECIMAL(7,4),
ALTER COLUMN "cashPct" SET DATA TYPE DECIMAL(7,4);

-- AlterTable
ALTER TABLE "UpcomingEvent" ALTER COLUMN "budgetCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "reservedCzk" SET DATA TYPE DECIMAL(14,2);

-- AlterTable
ALTER TABLE "UserProfile" ALTER COLUMN "monthlyNetIncomeCzk" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "emergencyFundTarget" SET DATA TYPE DECIMAL(14,2),
ALTER COLUMN "retirementMonthlyExpense" SET DATA TYPE DECIMAL(14,2);
